name: Release Windows Executable

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller youtube_chat_bot.py --name YoutubeChatBot.exe

      - name: Rename config.json
        run: ren config.json.template config.json

      - name: Rename prompts
        run: ren prompts\additional_requests_prompt.txt.template additional_requests_prompt.txt

      - name: Create release archive
        run: |
          $tagName = "${{ github.ref_name }}"
          $zipName = "YoutubeChatBot-$tagName.zip"
          Compress-Archive -Path dist\YoutubeChatBot.exe\YoutubeChatBot.exe, dist\YoutubeChatBot.exe\_internal, LICENSE, README.md, config.json, prompts -DestinationPath $zipName

      - name: Upload release archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./YoutubeChatBot-${{ github.ref_name }}.zip
          asset_name: YoutubeChatBot-${{ github.ref_name }}.zip
          asset_content_type: application/zip
